M48
; DRILL file {KiCad 7.0.10} date Tue Aug 20 03:51:06 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-20T03:51:06-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0295
%
G90
G05
T1
X5.9059Y-3.0386
X6.1335Y-3.0386
T2
X6.1555Y-4.7461
X6.1555Y-4.8543
M30
